name: solacers

services:
  mongodb:
    image: mongo:latest
    container_name: solacers-mongodb
    restart: unless-stopped
    ports:
      - '${MONGODB_PORT:-27093}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: solacers
    volumes:
      - mongodb_data:/data/db
    networks:
      - solacers

  redis:
    image: redis:8.2.1-alpine
    container_name: solacers-redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    sysctls:
      - net.core.somaxconn=1024
    command:
      - redis-server
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
      - --maxmemory
      - 256mb
      - --maxmemory-policy
      - allkeys-lru
      - --tcp-backlog
      - "511"
      - --timeout
      - "0"
      - --tcp-keepalive
      - "300"
      - --bind
      - "0.0.0.0"
    networks:
      - solacers

  web:
    image: ghcr.io/boaofdaeth/solacemetery:latest
    pull_policy: always
    container_name: solacers-web
    restart: unless-stopped
    network_mode: host
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: redis://localhost:${REDIS_PORT:-6379}
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started

  items:
    image: ghcr.io/boaofdaeth/solabase:latest
    pull_policy: always
    container_name: solacers-items
    restart: unless-stopped
    network_mode: host
    environment:
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:${MONGODB_PORT:-27093}/${MONGO_INITDB_DATABASE:-solacers}?authSource=admin
      REDIS_URL: redis://localhost:${REDIS_PORT:-6379}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      PORT: 2888
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  solacers:
    driver: bridge
